[compiler.solc]
exclude_paths = ["node_modules", "venv", ".venv", "lib", "script", "test"]
include_paths = ["node_modules"]
remappings = [
    "ds-test/=node_modules/ds-test/src/",
    "forge-std/=node_modules/forge-std/src/",
    "account-abstraction/=node_modules/@ERC4337/account-abstraction/contracts/",
    "account-abstraction-v0.6/=node_modules/@ERC4337/account-abstraction-v0.6/contracts/",
    "erc7579/=node_modules/erc7579/src/",
    "sentinellist/=node_modules/sentinellist/src/",
    "solmate/=node_modules/solmate/src/",
    "solady/=node_modules/solady/src/",
    "solarray/=node_modules/solarray/src/",
    "@rhinestone/modulekit/=node_modules/@rhinestone/modulekit/packages/modulekit/",
    "@rhinestone/sessionkeymanager/=node_modules/@rhinestone/modulekit/packages/sessionkeymanager/",
    "@rhinestone/=node_modules/@rhinestone/",
    "@safe-global/=node_modules/@safe-global/",
    "@ERC4337/=node_modules/@ERC4337/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@prb/math/=node_modules/@prb/math/",
    "erc4337-validation/=node_modules/erc4337-validation/src/",
]

[compiler.solc.optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["node_modules", "lib", "script"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""